name: advent_of_code
description: Solutions to Advent of Code 2023
version: 1.0.0

environment:
  sdk: '^3.0.0'

dependencies:
  matrices: any
  collection: ^1.15.0
  puzmat:
    git:
      url: https://github.com/UglyBob79/puzmat
      ref: master